Project ART/Controllers/SkillController.cs
using Project_ART.Data;
using Project_ART.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Routing.Matching;
using System.Dynamic;
using System.Net;
using System.Net.Mail;

namespace Project_ART.Controllers
{
    public class SkillController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public SkillController(ApplicationDbContext db, IHttpContextAccessor httpContextAccessor)
        {
            _db = db;
            _httpContextAccessor = httpContextAccessor;
        }

        public IActionResult Index()
        {
            dynamic obj = new ExpandoObject();
            bool deleteFlag = false;
            String tableName = "TableSkill";
            obj.Skill = _db.Skill.Where(x => x.Is_Deleted == deleteFlag);
            obj.Log = _db.Log.Where(x => x.Is_Deleted == deleteFlag && x.Table == tableName);

            return View(obj);
        }

        public IActionResult CreateSkill()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateSkill(TableSkill obj)
        {
            _db.Skill.Add(obj);
            _db.SaveChanges();

            //ADD LOG
            int? SessionId = _httpContextAccessor.HttpContext.Session.GetInt32("Id");
            DateTime now = DateTime.Now;
            String tableName = "TableSkill";
            String logDesc = "Created Skill";
            TableLog tableLog = new TableLog();
            tableLog.Table = tableName;
            tableLog.Table_ID = obj.Skill_ID;
            tableLog.Description = logDesc;
            tableLog.Date_Time = now.ToString("F");
            tableLog.User_ID = (int)SessionId;
            _db.Log.Add(tableLog);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }


        public IActionResult UpdateSkill(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var skillFromDb = _db.Skill.Find(id);

            if (skillFromDb == null)
            {
                return NotFound();
            }

            return View(skillFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateSkill(TableSkill obj)
        {
            _db.Skill.Update(obj);
            _db.SaveChanges();

            //ADD LOG
            int? SessionId = _httpContextAccessor.HttpContext.Session.GetInt32("Id");
            DateTime now = DateTime.Now;
            String tableName = "TableSkill";
            String logDesc = "Updated Skill";
            TableLog tableLog = new TableLog();
            tableLog.Table = tableName;
            tableLog.Table_ID = obj.Skill_ID;
            tableLog.Description = logDesc;
            tableLog.Date_Time = now.ToString("F");
            tableLog.User_ID = (int)SessionId;
            _db.Log.Add(tableLog);
            _db.SaveChanges();
            return RedirectToAction("Index");

        }

        [HttpGet]
        public IActionResult DeleteSkill(int? id)
        {
            bool skillFlag = true;
            var skillFromDb = _db.Skill.Find(id);
            var skill = new TableSkill() { Skill_ID = skillFromDb.Skill_ID, Is_Deleted = skillFlag };

            _db.Skill.Attach(skill);
            _db.Entry(skill).Property(x => x.Is_Deleted).IsModified = true;
            _db.SaveChanges();

            //ADD LOG
            int? SessionId = _httpContextAccessor.HttpContext.Session.GetInt32("Id");
            DateTime now = DateTime.Now;
            String tableName = "TableStatus";
            String logDesc = "Deleted Status";
            TableLog tableLog = new TableLog();
            tableLog.Table = tableName;
            tableLog.Table_ID = skillFromDb.Skill_ID;
            tableLog.Description = logDesc;
            tableLog.Date_Time = now.ToString("F");
            tableLog.User_ID = (int)SessionId;
            _db.Log.Add(tableLog);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Project ART/Views/Skill/CreateSkill.cshtml
@model TableSkill
@{
    ViewData["Title"] = "CreateSkill";
}


<div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <div class="col">
                    <div class="p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">Create Skill</h1>
                            <hr />
                        </div>
                        <form class="user" method="post">
                            <div class="form-group row">
                                <input asp-for="Data" type="text" class="form-control form-control-user"
                                       placeholder="Data" required>
                            </div>
                           
                            
                            
                            <hr>
                            <div class="form-group row">

                                <div class="col-sm-6 mb-3 mb-sm-0">

                                    <a asp-controller="Skill" asp-action="Index"  class="btn btn-danger btn-user btn-block">
                                        Cancel
                                    </a>
                                </div>
                                <div class="col-sm-6">
                                    <button type="submit" class="btn btn-primary btn-user btn-block">Create</button>
                                </div>
                            </div>
                            

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

Project ART/Views/Skill/Index.cshtml
@model dynamic
@{
    ViewData["Title"] = "Skill";
}


<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div class="row">
            <div class="col pt-2">
                <h3 class="m-0 font-weight-bold text-primary">Skill Table</h3>
            </div>

            <div class="col col-lg-2" align="right">
                <a asp-controller="Skill" asp-action="CreateSkill" class="btn btn-success btn-icon-split btn-lg">
                    <span class="icon text-white-50">
                        <i class="bi bi-plus-circle"></i>
                    </span>
                    <span class="text">Add</span>
                </a>
            </div>
        </div>

    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Skill ID</th>
                        <th>Skill</th>



                        <th style="text-align:center">Actions</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (TableSkill obj in Model.Skill)
                    {
                        <tr>
                            <td>@obj.Skill_ID</td>
                            <td>@obj.Data</td>



                            <td class="text-center">
                                <a asp-controller="Skill" asp-action="UpdateSkill" asp-route-id="@obj.Skill_ID" class="btn btn-info btn-block btn-sm" >
                                    <i class="bi bi-pencil-square"></i>
                                    Update
                                </a>
                                <a data-toggle="modal" data-target="#deleteModal-@obj.Skill_ID" class="btn btn-danger btn-block btn-sm">
                                    <i class="bi bi-trash3"></i>
                                    Delete
                                </a>
                            </td>
                        </tr>

                        <!-- Delete Modal-->
                        <div class="modal fade" id="deleteModal-@obj.Skill_ID" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                         aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Are you sure you want to Delete?</h5>
                                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">×</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">You will be deleting Skill Number @obj.Skill_ID</div>
                                    <div class="modal-footer">
                                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                                        <a class="btn btn-danger"  asp-controller="Skill" asp-action="DeleteSkill" asp-route-id="@obj.Skill_ID">Delete</a>
                                    </div>
                                </div>
                            </div>
                        </div>


                    }


                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- LOG TABLE -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div class="row">
            <div class="col pt-2">
                <h3 class="m-0 font-weight-bold text-primary">Log Table</h3>
            </div>

            <div class="col col-lg-2" align="right">
                <!--<a asp-controller="TableLog" asp-action="CreateLog" class="btn btn-success btn-icon-split btn-lg">
                    <span class="icon text-white-50">
                        <i class="bi bi-plus-circle"></i>
                    </span>
                    <span class="text">Add</span>
                </a>-->
            </div>
        </div>

    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Log ID</th>
                        <th>Table ID</th>
                        <th>Table</th>
                        <th>Description</th>
                        <th>Date</th>
                        <th>Updated By</th>




                        <th style="text-align:center">Actions</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (TableLog obj in Model.Log)
                    {
                        <tr>
                            <td>@obj.Log_ID</td>
                            <td>@obj.Table_ID</td>
                            <td>@obj.Table</td>
                            <td>@obj.Description</td>
                            <td>@obj.Date_Time</td>
                            <td>@obj.User_ID</td>


                            <td class="text-center">
                                <a asp-controller="TableLog" asp-action="UpdateLog" asp-route-id="@obj.Log_ID" class="btn btn-info btn-block btn-sm">
                                    <i class="bi bi-pencil-square"></i>
                                    Update
                                </a>
                                <a data-toggle="modal" data-target="#deleteModal-@obj.Log_ID" class="btn btn-danger btn-block btn-sm">
                                    <i class="bi bi-trash3"></i>
                                    Delete
                                </a>
                            </td>
                        </tr>

                        <!-- Delete Modal-->
                        <div class="modal fade" id="deleteModal-@obj.Log_ID" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                         aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Are you sure you want to Delete?</h5>
                                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">×</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">You will be deleting Log Number @obj.Log_ID</div>
                                    <div class="modal-footer">
                                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                                        <a class="btn btn-danger" asp-controller="TableLog" asp-action="DeleteLog" asp-route-id="@obj.Log_ID">Delete</a>
                                    </div>
                                </div>
                            </div>
                        </div>


                    }


                </tbody>
            </table>
        </div>
    </div>
</div>

@section Scripts {
    <!-- Page level plugins -->
    <script src="~/lib/datatables/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/js/demo/datatables-demo.js"></script>

}

Project ART/Views/Skill/UpdateSkill.cshtml
@model TableSkill
@{
    ViewData["Title"] = "Update Skill";
}


<div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <div class="col">
                    <div class="p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">Update Skill</h1>
                            <hr />
                        </div>
                        <form class="user" method="post" asp-action="UpdateSkill">
                            <input asp-for="Skill_ID"  hidden>
                            <div class="form-group row">
                                <input asp-for="Data" type="text" class="form-control form-control-user"
                                       placeholder="Data" required>
                            </div>


                            <hr>
                            <div class="form-group row">

                                <div class="col-sm-6 mb-3 mb-sm-0">

                                    <a asp-controller="Skill" asp-action="Index"  class="btn btn-danger btn-user btn-block">
                                        Cancel
                                    </a>
                                </div>
                                <div class="col-sm-6">
                                    <button type="submit" class="btn btn-primary btn-user btn-block">Update</button>
                                </div>
                            </div>
                            

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

</div>