Project ART/Controllers/CandidatesController.cs
using iTextSharp.text.pdf.parser;
using iTextSharp.text.pdf;
using Microsoft.AspNetCore.Mvc;
using Project_ART.Data;
using Project_ART.Models;
using System.Dynamic;
using System.Text;
using System.Net;
using System.Drawing.Imaging;
using System;
using System.Speech.Recognition;
using System.Speech.AudioFormat;
using MediaToolkit;
using MediaToolkit.Model;
using MediaToolkit.Options;
namespace Project_ART.Controllers
{
    public class CandidatesController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public CandidatesController(ApplicationDbContext db, IHttpContextAccessor httpContextAccessor)
        {
            _db = db;
            _httpContextAccessor = httpContextAccessor;
        }
        public IActionResult Index()
        {
            ViewBag.Scores = _db.Weighting.Find(1);
            bool deleteFlag = false;
            String tableName = "TableCandidate";
            IEnumerable<TableCandidate> obj = _db.Candidate.Where(x => x.Is_Deleted == deleteFlag);


            var Candidates =
                             from candidate in _db.Candidate.Where(x => x.Is_Deleted == false)
                             join job in _db.JobApplication.Where(x => x.Is_Deleted == false) on candidate.Job_Application_ID equals job.Job_Application_ID
                             join resume in _db.Resume.Where(x => x.Is_Deleted == false) on candidate.Resume_ID equals resume.Resume_ID
                             join assessment in _db.Assessment on candidate.Assessment_ID equals assessment.Assessment_ID
                             join exam in _db.Exam on assessment.Assessment_ID equals exam.Exam_ID
                             join interview in _db.Interview on assessment.Assessment_ID equals interview.Interview_ID
                             join introduction in _db.Introduction on candidate.Introduction_ID equals introduction.Introduction_ID
                             select new
                             {
                                 Candidate_ID = candidate.Candidate_ID,
                                 Job = job.Job,
                                 First_Name = candidate.First_Name,
                                 Last_Name = candidate.Last_Name,
                                 Middle_Initial = candidate.Middle_Initital,
                                 Email = candidate.Email,
                                 DISC = introduction.DISC_Trait,
                                 Resume_Score = resume.Resume_Score,
                                 Photo = candidate.Photo,
                                 Exam = exam.Exam_Score,
                                 Interview = interview.Interview_Score,
                             };
            var weighting = _db.Weighting.Find(1);
            double personalityScore = (double)(weighting.Personality);
            double resumeScore = (double)(weighting.Resume) * .01;
            double examScore = (double)(weighting.Exam) * .01;
            double interviewScore = (double)(weighting.Interview) * .01;
            foreach (var i in Candidates)
            {

                var sampleData = new MLCandidateRanking.ModelInput()
                {
                    DISC_Personality = i.DISC,
                    Resume_Score = (float)i.Resume_Score,
                };


                //Load model and predict output
                var result = MLCandidateRanking.Predict(sampleData).Score;

                if (i.Exam == 0 || i.Interview == 0)
                {
                    var finalResult = "NA";
                    TempData[i.Candidate_ID.ToString()] = finalResult.ToString();
                    TempData[i.Candidate_ID.ToString() + "rank"] = (100 - i.Resume_Score).ToString() + finalResult.ToString();
                }
                else
                {
                    var finalResult = (int)(result[1] * personalityScore + (i.Resume_Score * resumeScore) + (i.Exam * examScore) + (i.Interview * interviewScore));
                    TempData[i.Candidate_ID.ToString()] = finalResult.ToString() + "%";
                    TempData[i.Candidate_ID.ToString() + "rank"] = ((100 - finalResult) * .1).ToString();
                }

            }
            ViewBag.Candidate = Candidates.ToList();

            return View();
        }

        public IActionResult ViewCandidate(int? id)
        {
            var candidate = _db.Candidate.Find(id);
            ViewBag.Candidates = candidate;

            ViewBag.MatchedSkills = _db.Data.Where(x => x.Resume_ID == candidate.Resume_ID && x.Is_Deleted == false && x.Skill_Matched == true);
            ViewBag.OtherSkills = _db.Data.Where(x => x.Resume_ID == candidate.Resume_ID && x.Is_Deleted == false && x.Skill_Matched == false);
            var assessmentID = _db.Assessment.Find(candidate.Assessment_ID);
            var exam = _db.Exam.Find(assessmentID.Exam_ID);
            var interview = _db.Interview.Find(assessmentID.Assessment_ID);

            ViewBag.Exam = exam.Exam_Score;
            ViewBag.Interview = interview.Interview_Score;

            return View();
        }

        [HttpGet]
        public IActionResult DeleteCandidate(int? id)
        {
            var candidate = _db.Candidate.Find(id);
            candidate.Is_Deleted = true;
            _db.Candidate.Update(candidate);
            _db.SaveChanges();

            //ADD LOG
            int? SessionId = _httpContextAccessor.HttpContext.Session.GetInt32("Id");
            DateTime now = DateTime.Now;
            String tableName = "TableCandidate";
            String logDesc = "Deleted Candidate";
            TableLog tableLog = new TableLog();
            tableLog.Table = tableName;
            tableLog.Table_ID = candidate.Candidate_ID;
            tableLog.Description = logDesc;
            tableLog.Date_Time = now.ToString("F");
            tableLog.User_ID = (int)SessionId;
            _db.Log.Add(tableLog);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult UploadCandidate()
        {
            ViewBag.Jobs = _db.JobApplication.Where(x => x.Is_Deleted == false && x.Is_Open == true);

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SubmitAssessment()
        {

            var data = Request.Form;

            int candidateID = Int32.Parse(data["candidateID"]);
            var score = Int32.Parse(data["score"]);

            var candidate = _db.Candidate.Find(candidateID);
            var assessment = _db.Assessment.Find(candidate.Assessment_ID);
            var exam = _db.Exam.Find(assessment.Exam_ID);

            exam.Exam_Score = score;
            _db.Exam.Update(exam);
            _db.SaveChanges();


            return Json(HttpStatusCode.BadRequest);
        }


        [HttpPost]
        public async Task<IActionResult> SubmitInterview()
        {

            var data = Request.Form;

            int candidateID = Int32.Parse(data["candidateID"]);
            var score = Int32.Parse(data["score"]);

            var candidate = _db.Candidate.Find(candidateID);
            var assessment = _db.Assessment.Find(candidate.Assessment_ID);
            var interview = _db.Interview.Find(assessment.Exam_ID);

            interview.Interview_Score = score;
            _db.Interview.Update(interview);
            _db.SaveChanges();


            return Json(HttpStatusCode.BadRequest);
        }

        [HttpPost]
        public async Task<IActionResult> SaveCandidateDetails()
        {

            var data = Request.Form;
            if (Request.Form.Files.Any())
            {


                TableResume resume = new TableResume();
                TableIntroduction introduction = new TableIntroduction();
                TableExam exam = new TableExam { Exam_Score = 0 };
                TableInterview interview = new TableInterview { Interview_Score = 0 };

                TableAssessment assessment = new TableAssessment { Exam = exam, Interview = interview };

                TableCandidate candidate = new TableCandidate { Resume = resume, Introduction = introduction, Assessment = assessment };
                candidate.First_Name = data["First Name"];
                candidate.Last_Name = data["Last Name"];
                string MI = data["Middle Initial"];
                candidate.Middle_Initital = MI.ToUpper().ToCharArray()[0];
                candidate.Email = data["Email"];
                candidate.Mobile_Number = data["Mobile Number"];
                candidate.Website = data["Website"];
                candidate.Province = data["Province"];
                candidate.City = data["City"];
                int jobID = int.Parse(data["JobID"]);
                candidate.Job_Application_ID = jobID;
                candidate.Email_Confirmed = true;
                _db.Candidate.Add(candidate);
                _db.SaveChanges();

                TableStatus status = new TableStatus();
                status.Candidate = candidate;
                _db.Status.Add(status);
                _db.SaveChanges();

                string fileName = candidate.Candidate_ID + candidate.Last_Name + "_" + candidate.First_Name;
                candidate.Photo = fileName + ".png";
                introduction.Introduction_Video = fileName + ".webm";
                resume.Resume = fileName + ".pdf";
                _db.Candidate.Update(candidate);


                

                var photo = Request.Form.Files["Photo"];
                var cv = Request.Form.Files["Resume"];
                var video = Request.Form.Files["Introduction Video"];

                if (photo != null && cv != null && video != null)
                {

                    string UploadFolder = System.IO.Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "UploadedFiles");

Project ART/Views/Candidates/UploadCandidate.cshtml
@{
    ViewData["Title"] = "Upload Candidate";
}


<div class="main-body">
    <div class="card shadow mb-4">
        <div class="card-header py-3 ">
            <div class="row">
                <div class="col pt-2 mb-3">
                    <h3 class="m-0 font-weight-bold text-primary">Create Candidate</h3>
                </div>
            </div>


            <div class="row gutters-md ">
                <div class="col-md-4 mb-3">
                    <div class="card">
                        <div class="card-body my-5 py-5">
                            <div class="d-flex flex-column align-items-center text-center">
                                
                                <a href="#" id="changeImage" class="">

                                    <div class="container-image">

                                        <img src="~/img/default.png" alt="Admin" id="profilePic" class="rounded-circle image-change" width="160" height="160">
                                        <div class="middle">
                                            <div class="text-change"><i class="bi bi-upload"></i></div>
                                        </div>
                                    </div>

                                    <input id='imageUpload' type='file' accept="image/*" hidden />
                                </a>
                                <h5 class="text-secondary">Add Profile Picture</h5>
                            </div>
                        </div>
                    </div>

                </div>

                <div class="col-md-8">
                    <div class="card mb-3">
                        <div class="card-body">
                            
                                <div class="row mb-3">

                                    <div class="col-sm-3">
                                        <h6 class="mt-2">First Name</h6>
                                    </div>


                                    <input  type="text" id="profpic" hidden class="form-control"
                                           placeholder="Profile Pic" required>


                                    <div class="col-sm-9 text-secondary">
                                        <input id="firstName"  type="text" class="form-control"
                                               placeholder="First Name" required>
                                    </div>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-sm-3">
                                        <h6 class="mt-2">Last Name</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        <input id="lastName" type="text" class="form-control"
                                               placeholder="Last Name" required>
                                    </div>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-sm-3">
                                        <h6 class="mt-2">Middle Initial</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        <input id="mi" type="text" class="form-control"
                                               placeholder="Middle Initial" required>
                                    </div>
                                </div>
                                <hr>

                                <div class="row">
                                    <div class="col-sm-3">
                                        <h6 class="mt-2">Email</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        <input id="email" type="email" class="form-control"
                                               placeholder="Email" required>
                                    </div>
                                </div>

                                <hr>

                                <div class="row">
                                    <div class="col-sm-3">
                                        <h6 class="mt-2">Mobile</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        <input id="mobileNumber"  type="number" class="form-control"
                                               placeholder="Mobile Number" required>
                                    </div>
                                </div>
                                <hr>



                                <div class="row">
                                    <div class="col-sm-3">
                                        <h6 class="mt-2">Website</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        <input id="website" type="text" class="form-control"
                                               placeholder="Website" required>
                                    </div>
                                </div>

                                <hr>


                                <div class="row">
                                    <div class="col-sm-3">
                                        <h6 class="mt-2">Province</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        <select name="Province" class="form-control" id="province" required></select>
                                    </div>
                                </div>
                                <hr>

                                <div class="row">
                                    <div class="col-sm-3">
                                        <h6 class="mt-2">City</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        <select name="City" class="form-control" id="city" required></select>
                                    </div>
                                </div>
                                <hr>

                                <div class="row">
                                    <div class="col-sm-3">
                                        <h6 class="mt-2">Resume</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                    <input type="file" class="form" id="ResumeInput"
                                               placeholder="Resume" required accept=".pdf">
                                    </div>
                                </div>

                                <hr>
                                 <div class="row">
                                    <div class="col-sm-3">
                                        <h6 class="mt-2">Video</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                    <input type="file" class="form" id="introductionVideo"
                                               placeholder="Video" required accept=".webm">
                                    </div>
                                </div>
                                <hr>
                              
                                
                                <div class="row">
                                    <div class="col-sm-3">
                                        <h6 class="mt-2">Job</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        <select  class="form-control"  id="JobID">
                                        <option disabled selected value="0">Select Job Listing</option>
                                        @foreach(var job in @ViewBag.Jobs){
                                        <option value="@job.Job_Application_ID">@job.Job</option>
                                        }
                                            
                                        </select>
                                    </div>
                                </div>
                                <hr>
                                 



                                <div class="row align-items-end">
                                    <div class="col-lg-8">
                                    </div>
                                    <div class="col col-lg-2">
                                        <a asp-controller="Candidates" asp-action="Index" class="btn btn-danger btn-icon-split btn-lg" id="Cancel">
                                            <span class="icon text-white-50">
                                                <i class="bi bi-x-square"></i>
                                            </span>
                                            <span class="text">Cancel</span>
                                        </a>
                                    </div>

                                    <div class="col col-lg-2">
                                    <button class="btn btn-success btn-icon-split btn-lg" id="btnSubmit">
                                            <span class="icon text-white-50">
                                                <i class="bi bi-check2-square"></i>
                                            </span>
                                            <span id="spinner" class="text ml-2 mr-2">Add</span>
                                        </button>
                                    </div>
                                </div>
                            
                        </div>

                    </div>




                </div>





            </div>

        </div>
    </div>

</div>
<script src="~/js/demo/changeImage.js"></script>
<script src="~/js/UploadCandidate.js"></script>
<script src="~/js/city.js" asp-append-version="true" async></script>
<script src="~/js/cityFunction.js" asp-append-version="true" async></script>